name: test pipeline
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6
        with:
          ref: main
          
      - name: install python and cache 
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: python code
        run: |
          ls 
          pwd
          python3 -m venv venv
          source venv/bin/activate
          pip3 install -r requirements.txt
          python3 app.py
          
          
