name: connect ec2
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: connect-ec2
        run: |
          echo "${{ secrets.PEM }}" > key.pem
          chmod 400 key.pem
          ssh -i key.pem ec2-user@3.7.252.60
          whoami
